add_subdirectory(animation)
add_subdirectory(application)
add_subdirectory(artwork)
add_subdirectory(attract)
add_subdirectory(cache)
add_subdirectory(database)
add_subdirectory(detailpage)
add_subdirectory(event)
add_subdirectory(filter)
add_subdirectory(gamepad)
add_subdirectory(interaction)
add_subdirectory(kart)
add_subdirectory(keyboard)
add_subdirectory(launch)
add_subdirectory(mouse)
add_subdirectory(navigation)
add_subdirectory(overlay)
add_subdirectory(playlist)
add_subdirectory(query)
add_subdirectory(restore)
add_subdirectory(scroll)
add_subdirectory(search)
add_subdirectory(selection)
add_subdirectory(session)
add_subdirectory(settings)
add_subdirectory(detailspane)
add_subdirectory(viewport)
add_subdirectory(widgetpool)
