add_subdirectory(animation)
add_subdirectory(attract)
add_subdirectory(event)
add_subdirectory(filter)
add_subdirectory(gamepad)
add_subdirectory(interaction)
add_subdirectory(keyboard)
add_subdirectory(launch)
add_subdirectory(mouse)
add_subdirectory(navigation)
add_subdirectory(overlay)
add_subdirectory(scroll)
add_subdirectory(search)
add_subdirectory(selection)
add_subdirectory(viewport)
add_subdirectory(widgetpool)
