add_subdirectory(cache)
add_subdirectory(database)
add_subdirectory(dat)
add_subdirectory(dataudit)
add_subdirectory(import)
add_subdirectory(kart)
add_subdirectory(playlist)
add_subdirectory(query)
add_subdirectory(restore)
add_subdirectory(scraper)
add_subdirectory(session)
add_subdirectory(settings)
add_subdirectory(watcher)
